"""
Turns the Product Manager agent's output into tool-neutral backlog items, and renders each one for the tool that will
receive it (Jira: Atlassian Document Format, Azure DevOps: HTML).

Epic  = one product module        Story = one user story (US-nnn), titled with its ID so it stays traceable to the docs.
"""

from __future__ import annotations

import hashlib
import json
import re
from html import escape

from context import AgentRole, ProjectContext

PRIORITY_NAMES = {"high": "High", "medium": "Medium", "low": "Low"}


def _list(v) -> list[str]:
    if v is None:
        return []
    if isinstance(v, (list, tuple)):
        return [str(x).strip() for x in v if str(x).strip()]
    s = str(v).strip()
    return [] if s.lower() in ("", "none", "n/a", "[]") else [s]


def _text(v) -> str:
    s = str(v or "").strip()
    return "" if s.lower() in ("none", "n/a") else s


def _label(s: str) -> str:
    """Jira labels cannot contain spaces; ADO tags are free text but the same form keeps them consistent."""
    return re.sub(r"[^A-Za-z0-9_.-]+", "-", str(s)).strip("-")[:50]


def build_backlog(context: ProjectContext) -> dict:
    pm = context.get_contribution(AgentRole.PRODUCT_MANAGER)
    out = (pm.output if pm else {}) or {}
    prios = {p.get("story_id"): p for p in out.get("priorities", []) if isinstance(p, dict)}
    epics_by_id = {e["id"]: e for e in out.get("epics", []) if e.get("id")}

    stories = []
    for s in out.get("stories", []):
        if not s.get("id"):
            continue
        epic = epics_by_id.get(s.get("epic_id"), {})
        prio = PRIORITY_NAMES.get(str((prios.get(s["id"]) or {}).get("priority", "")).lower(), "Medium")
        item = {
            "id": s["id"], "kind": "story", "epic_id": s.get("epic_id", ""),
            "title": f"{s['id']} · {_text(s.get('feature')) or _text(s.get('story'))[:80]}"[:250],
            "priority": prio, "role": _text(s.get("role")),
            "story": _text(s.get("story")), "business_value": _text(s.get("business_value")),
            "preconditions": _text(s.get("preconditions")), "trigger": _text(s.get("trigger")),
            "main_flow": _list(s.get("main_flow")), "alternative_flow": _text(s.get("alternative_flow")),
            "exception_flow": _text(s.get("exception_flow")), "business_rules": _list(s.get("business_rules")),
            "acceptance_criteria": _list(s.get("acceptance_criteria")), "edge_cases": _list(s.get("edge_cases"))[:8],
            "dependencies": [d for d in _list(s.get("dependencies")) if re.match(r"^US-\d+$", d)],
            "fr_ids": _list(s.get("related_fr_ids")),
            "labels": ["ai-generated"] + [_label(epic.get("name", ""))] + [_label(f) for f in _list(s.get("related_fr_ids"))],
        }
        item["labels"] = [x for x in dict.fromkeys(item["labels"]) if x]
        item["hash"] = hashlib.sha1(json.dumps({k: v for k, v in item.items() if k != "hash"}, sort_keys=True).encode()).hexdigest()[:12]
        stories.append(item)

    epics = []
    for e in out.get("epics", []):
        item = {"id": e["id"], "kind": "epic", "title": f"{e['id']} · {_text(e.get('name'))}"[:250], "name": _text(e.get("name")),
                "description": _text(e.get("description")), "labels": ["ai-generated"],
                "story_count": sum(1 for s in stories if s["epic_id"] == e["id"])}
        item["hash"] = hashlib.sha1(json.dumps(item, sort_keys=True).encode()).hexdigest()[:12]
        epics.append(item)
    return {"epics": epics, "stories": stories}


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------
def _sections(it: dict) -> list[tuple[str, str, list[str] | str]]:
    """(heading, kind, content) — kind is 'p' paragraph, 'ul' bullets, 'ol' numbered."""
    if it["kind"] == "epic":
        return [("", "p", it["description"])] if it["description"] else []
    out = [("", "p", it["story"]), ("Business value", "p", it["business_value"]), ("Preconditions", "p", it["preconditions"]),
           ("Trigger", "p", it["trigger"]), ("Main flow", "ol", it["main_flow"]),
           ("Alternative flow", "p", it["alternative_flow"]), ("Exception flow", "p", it["exception_flow"]),
           ("Business rules", "ul", it["business_rules"]), ("Edge cases", "ul", it["edge_cases"])]
    return [x for x in out if x[2]]


def _trace(it: dict) -> str:
    bits = []
    if it.get("fr_ids"):
        bits.append("Source requirement(s): " + ", ".join(it["fr_ids"]))
    if it.get("dependencies"):
        bits.append("Depends on: " + ", ".join(it["dependencies"]))
    bits.append(f"Backlog ID {it['id']} — generated by the AI product team; edit freely in this tool.")
    return " · ".join(bits)


def to_html(it: dict, with_acceptance: bool = False) -> str:
    """HTML for Azure DevOps. Acceptance criteria go in their own field where the process has one (see to_acceptance_html)."""
    h = []
    for head, kind, body in _sections(it):
        if head:
            h.append(f"<h3>{escape(head)}</h3>")
        if kind == "p":
            h.append(f"<p>{escape(body)}</p>")
        else:
            tag = "ol" if kind == "ol" else "ul"
            h.append(f"<{tag}>" + "".join(f"<li>{escape(x)}</li>" for x in body) + f"</{tag}>")
    if with_acceptance and it.get("acceptance_criteria"):
        h.append("<h3>Acceptance criteria</h3>" + to_acceptance_html(it))
    h.append(f"<p><i>{escape(_trace(it))}</i></p>")
    return "".join(h)


def to_acceptance_html(it: dict) -> str:
    return "<ul>" + "".join(f"<li>{escape(x)}</li>" for x in it.get("acceptance_criteria", [])) + "</ul>"


def _adf_text(t: str, bold=False, italic=False) -> dict:
    n = {"type": "text", "text": t}
    marks = ([{"type": "strong"}] if bold else []) + ([{"type": "em"}] if italic else [])
    if marks:
        n["marks"] = marks
    return n


def to_adf(it: dict) -> dict:
    """Atlassian Document Format (Jira Cloud REST v3 requires it for description)."""
    para = lambda t, **k: {"type": "paragraph", "content": [_adf_text(t, **k)]}
    li = lambda t: {"type": "listItem", "content": [para(t)]}
    c = []
    for head, kind, body in _sections(it):
        if head:
            c.append({"type": "heading", "attrs": {"level": 3}, "content": [_adf_text(head)]})
        if kind == "p":
            c.append(para(body))
        else:
            c.append({"type": "orderedList" if kind == "ol" else "bulletList", "content": [li(x) for x in body]})
    if it.get("acceptance_criteria"):
        c.append({"type": "heading", "attrs": {"level": 3}, "content": [_adf_text("Acceptance criteria")]})
        c.append({"type": "bulletList", "content": [li(x) for x in it["acceptance_criteria"]]})
    c.append(para(_trace(it), italic=True))
    return {"type": "doc", "version": 1, "content": c}
